name: Publish
on:
  release:
    types: [published]
jobs:
  go-get:
    name: go get
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v18
      - name: Fetch release from proxy
        run: >-
          nix-shell --pure
          --keep GITHUB_REF
          --run 'go get -d zombiezen.com/go/oauth2@"$(echo "$GITHUB_REF" | sed -e s:^refs/tags/:: )"'
